version: 2.1
jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: echo "Hello, World!"
  sonarqube:
    docker:
      - image: sonarsource/sonar-scanner-cli
    working_directory: ~/build
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Install findutils"
          command: apk add --no-cache findutils
      - run:
          name: "List project files"
          command: find .
      - run:
          name: "Run SonarQube Analysis"
          command: |
            SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
            echo "Sonar branch value is: $SONAR_BRANCH"
            echo "Sonar org value is: $SONAR_ORG"
            sonar-scanner \
              -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
              -Dsonar.organization="$SONAR_ORG" \
              -Dsonar.host.url="https://sonarcloud.io" \
              -Dsonar.exclusions="**/android/**,**/ios/**" \
              -Dsonar.login="$SONAR_TOKEN" \
              -Dsonar.branch.name="$SONAR_BRANCH" \
              -Dsonar.sources="."
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - sonarqube
